# This file was generated by GoReleaser. DO NOT EDIT.
cask "cv" do
  name "cv"
  desc "CognitiveVault CLI - manage knowledge vaults from the terminal"
  homepage "https://cognitive-vault.com"
  version "0.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cv"

  on_macos do
    on_intel do
      url "https://github.com/SimplyLiz/cognitive-vault/releases/download/v#{version}/cv_#{version}_darwin_amd64.tar.gz"
      sha256 "695f25631cd0174b633e749e239bae15fbe3667b0a7f2e05673b4b102e11be48"
    end
    on_arm do
      url "https://github.com/SimplyLiz/cognitive-vault/releases/download/v#{version}/cv_#{version}_darwin_arm64.tar.gz"
      sha256 "925ea86deb2a7ffac0afe7066d8a9d271882cc2361f3c571c98ed27ff6033628"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/SimplyLiz/cognitive-vault/releases/download/v#{version}/cv_#{version}_linux_amd64.tar.gz"
      sha256 "b4f407fc56d57b90f1d85de06504ddc0a7668ea4dbebfaf9e3cf5234085c23e6"
    end
    on_arm do
      url "https://github.com/SimplyLiz/cognitive-vault/releases/download/v#{version}/cv_#{version}_linux_arm64.tar.gz"
      sha256 "d9a6b61d9ac309c0413bffd42a3bcb2d58d34c2db9a343313ab27602a04bfa6f"
    end
  end

  # No zap stanza required
end
