# This file was generated by GoReleaser. DO NOT EDIT.
cask "cv" do
  name "cv"
  desc "CognitiveVault CLI - manage knowledge vaults from the terminal"
  homepage "https://cognitive-vault.com"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cv"

  on_macos do
    on_intel do
      url "https://github.com/SimplyLiz/cognitive-vault/releases/download/v#{version}/cv_#{version}_darwin_amd64.tar.gz"
      sha256 "61b3acfa52e7c58544f91228006e6f09a12dc2a302aa7bad5c02ce61792ad14f"
    end
    on_arm do
      url "https://github.com/SimplyLiz/cognitive-vault/releases/download/v#{version}/cv_#{version}_darwin_arm64.tar.gz"
      sha256 "7ef62675610f789913bec58648f1d409a08060cf4cf175a76dada13be8eaef03"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/SimplyLiz/cognitive-vault/releases/download/v#{version}/cv_#{version}_linux_amd64.tar.gz"
      sha256 "3311562d256d9819e35c17245bf3d2de07482bc78dd448897d916c3837c9e947"
    end
    on_arm do
      url "https://github.com/SimplyLiz/cognitive-vault/releases/download/v#{version}/cv_#{version}_linux_arm64.tar.gz"
      sha256 "574d3bb5aacdbd4213c81676db413e004eb17aecea5043014a398dcf43faaba0"
    end
  end

  # No zap stanza required
end
